---
# tasks file for ansible-maestro-java
- name: Ensure that maestro client dependencies are installed (RPM-based)
  tags:
    - maestro
    - dependencies
  when:
    - ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat' or ansible_distribution == 'Fedora'
  package: name="{{ maestro_rdb_dependencies }}" state=present

- name: Create Maestro client user
  tags:
    - maestro
    - user
  shell: id {{ maestro_rdb_user }} || (useradd -m -U {{ maestro_rdb_user }}  )

- debug:
    msg: "Going to download & use maestro from {{ maestro_rdb_download_url }}"

- name: Download Maestro client from {{ maestro_rdb_download_url }}
  tags:
    - maestro
    - download
  get_url:
    url: "{{ maestro_rdb_download_url }}"
    dest: "{{ maestro_rdb_download_dest }}/{{ maestro_rdb_download_url | basename}}"
    force: yes
  register: dist_get

- name: Unzip downloaded distribution to {{ maestro_rdb_install_dest }}
  tags:
    - maestro
    - unarchive
  unarchive:
    src: "{{ maestro_rdb_download_dest }}/{{ maestro_rdb_download_url | basename }}"
    dest: "{{ maestro_rdb_install_dest }}/"
    remote_src: True
    list_files: yes
  register: archive_contents

- debug: msg="Latest maestro client directory created is {{ archive_contents.files[0] | dirname | dirname }}"
  tags:
  - maestro
  - link

- name: Create link to maestro install dir {{ maestro_rdb_install_dest }}/{{ maestro_rdb_install_link }}
  tags:
    - maestro
    - link
  file:
    src: "{{ maestro_rdb_install_dest }}/{{ archive_contents.files[0] | dirname | dirname  }}"
    dest: "{{ maestro_rdb_install_dest }}/{{ maestro_rdb_install_link }}"
    state: link
    mode: 0755
    owner: "{{ maestro_rdb_user }}"
    group: "{{ maestro_rdb_user }}"
    force: true

- name: Create log directory
  tags:
    - maestro
    - logdir
  file:
    path: "{{ maestro_rdb_log_dir }}"
    state: directory
    owner: "{{ maestro_rdb_user }}"
    group: "{{ maestro_rdb_user }}"
    mode: 0755

- name: Create user configuration directory
  tags:
    - maestro
    - configure
  file:
    path: "/home/{{ maestro_rdb_user }}/.maestro"
    state: directory
    owner: "{{ maestro_rdb_user }}"
    group: "{{ maestro_rdb_user }}"
    mode: 0755

- name: Configure maestro java DB access
  tags:
    - maestro
    - configure
  template:
    src: templates/maestro-results.properties.j2
    dest: "/home/{{ maestro_rdb_user }}/.maestro/maestro-results.properties.j2"
    owner: "{{ maestro_rdb_user }}"
    group: "{{ maestro_rdb_user }}"
    mode: 0700

- name: Ensure correct ownership
  tags:
    - maestro
    - ownership
  shell: chown -R "{{ maestro_rdb_user }}":"{{ maestro_rdb_user }}" {{ maestro_rdb_install_dest }}/maestro*
